version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "traffic-check"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-yfxarqj2sgfp"
s3_prefix = "traffic-check"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
